pipeline {
  agent {
    node {
      label 'local'
    }
  }
  triggers {
    pollSCM 'H/30 * * * *'
  }
  options{
    buildDiscarder(logRotator(numToKeepStr: '5', daysToKeepStr: '5'))
    timestamps()
  }
  environment {
    SECRET_FILE = credentials('terraform-secrets')
    TF_IN_AUTOMATION = 'true'
  }
  stages {
    stage('clone repo') {
      steps {
        git branch: 'main', url: 'https://github.com/Ax-Projects/DevOps-Demos'
        // git branch: 'main', url: 'https://github.com/Ax-Projects/DealBot'
      }
    }
    stage('copy secrets') {
      steps{
        sh 'cp $SECRET_FILE DealBot-Jenkins'
        sh 'chmod +r DealBot-Jenkins/secret.tfvars'
      }
      // steps {
      //   script {
      //       echo "$PWD";
      //       fileOperations([[$class 'CopyOperation', from: '~/secrets/secret.tfvars', into: './secret.tfvars']])
      //   }
      // }
    }
    stage('init terraform') {
      steps {
        sh(script: "cd DealBot-Jenkins && terraform init")
      }
    }
    stage('terraform plan') {
      steps {
        sh(script: "cd DealBot-Jenkins && terraform plan -var-file=secret.tfvars")
      }
    }
  }
}