pipeline {
  agent {
    node {
      label 'local'
    }
  }
  options{
    buildDiscarder(logRotator(numToKeepStr: '5', daysToKeepStr: '5'))
    timestamps()
  }
  environment {
    SECRET_FILE = credentials('terraform-secrets')
    TELEGRAM_TOKEN = credentials('telegram-token')
    TF_IN_AUTOMATION = 'true'
  }
  stages {
    stage('clone repo') {
      steps {
        git branch: 'main', url: 'https://github.com/Ax-Projects/DevOps-Demos'
      }
    }
    stage('copy secrets') {
      steps{
        sh 'cp $SECRET_FILE DealBot-Jenkins'
        sh 'cp $TELEGRAM_TOKEN DealBot-Jenkins'
        sh 'chmod +r DealBot-Jenkins/secret.tfvars'
        sh 'chmod +r DealBot-Jenkins/keys.py'
      }
    }
    stage('init terraform') {
      steps {
        sh(script: "cd DealBot-Jenkins && terraform init")
      }
    }
    stage('terraform plan') {
      steps {
        sh(script: "cd DealBot-Jenkins && terraform plan -var-file=secret.tfvars -out=tfplan")
      }
    }
    stage('terraform apply') {
      steps {
        sh(script: "cd DealBot-Jenkins && terraform apply -input=false -auto-approve tfplan")
      }
    }
    stage('Ansible Provisioning') {
      steps{
        sh 'cd DealBot-Jenkins && ansible-playbook -i inventory.ini dealbot.yml'
      }
    }
    
    stage('terraform destroy') {
      steps {
        sh(script: "cd DealBot-Jenkins && terraform destroy -input=false -auto-approve -var-file=secret.tfvars")
      }
    }
  }
  // post {
  //   failure {
  //     cleanup {
  //       deleteDir()
  //     }
  //   }
  // }
}